//  ___FILEHEADER___

import RxSwift

class ___FILEBASENAMEASIDENTIFIER___ {

}

// MARK: - ___FILEBASENAMEASIDENTIFIER___IO
extension ___FILEBASENAMEASIDENTIFIER___: ___FILEBASENAMEASIDENTIFIER___IO {

}
